//
//  SLKMediaProcesserCommon.h
//  MediaStreamer
//
//  Created by Think on 2016/11/29.
//  Copyright © 2016年 Cell. All rights reserved.
//

#import <Foundation/Foundation.h>

enum slk_media_processer_info_type {
    //    MEDIA_PROCESSER_INFO_PROCESS_PERCENT = 0,
    SLK_MEDIA_PROCESSER_INFO_WRITE_TIMESTAMP = 1,
};

enum slk_media_processer_error_type {
    SLK_MEDIA_PROCESSER_ERROR_OPEN_INPUT_FILE_FAIL = 0,
    SLK_MEDIA_PROCESSER_ERROR_OPEN_VIDEO_DECODER_FAIL = 1,
    SLK_MEDIA_PROCESSER_ERROR_OPEN_AUDIO_DECODER_FAIL = 2,
    SLK_MEDIA_PROCESSER_ERROR_OPEN_AUDIO_PREPROCESS_FAIL = 3,
    SLK_MEDIA_PROCESSER_ERROR_OPEN_VIDEO_ENCODER_FAIL = 4,
    SLK_MEDIA_PROCESSER_ERROR_OPEN_AUDIO_ENCODER_FAIL = 5,
    SLK_MEDIA_PROCESSER_ERROR_OPEN_OUTPUT_FILE_FAIL = 6,
    
    SLK_MEDIA_PROCESSER_ERROR_READ_INPUT_FILE_FAIL = 10,
    SLK_MEDIA_PROCESSER_ERROR_VIDEO_DECODE_FAIL = 11,
    SLK_MEDIA_PROCESSER_ERROR_COLORSPACECONVERT_FAIL  = 12,
    SLK_MEDIA_PROCESSER_ERROR_VIDEO_ENCODE_FAIL  = 13,
    SLK_MEDIA_PROCESSER_ERROR_AUDIO_DECODE_FAIL = 14,
    SLK_MEDIA_PROCESSER_ERROR_AUDIO_ENCODE_FAIL = 15,
    SLK_MEDIA_PROCESSER_ERROR_AUDIO_MIX_FAIL = 16,
    
    SLK_MEDIA_PROCESSER_ERROR_WRITE_OUTPUT_FILE_FAIL = 18,
    
    SLK_MEDIA_PROCESSER_ERROR_SEEK_INPUT_FILE_FAIL = 19,
    
    SLK_MEDIA_PROCESSER_ERROR_SAVE_PNG_FAIL = 20,
    
    SLK_MEDIA_PROCESSER_ERROR_WRITE_GIF_FAIL = 21,
    
    SLK_MEDIA_PROCESSER_ERROR_REMUX_FAIL = 100,
};
